type_name:
  allowed_symbols: "_"
identifier_name:

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
disabled_rules:
    - multiple_closures_with_trailing_closure

